### PR TITLE
#162563775 A user can create an account

### PR DESCRIPTION
**Pull request by tirgei**
#### What does this PR do?
This Pull Request creates a register page through which a new user can sign up on the platform

#### Description of Task to be completed?
The tasks for this PR is:
- Create a form for user to input details using HTML
- Style the details form using CSS

#### How should this be manually tested?
Clone this repository on your machine:
```$ git clone https://github.com/tirgei/stack-overflow-lite.git ```

CD into the project folder on your machine
```$ cd stack-overflow-lite ```

Check out the branch for this PR
``` $ git branch ft-user-register-162563775 ```

Open the `register.html` file on your browser

### Pivotal Tracker story associated with this PR
From [StackOverflow-lite](https://www.pivotaltracker.com/n/projects/2231260) project, story: #162563775

#### Screenshot
register-stack-overflow-lite

### CODE REVIEW

**Comment by jmusila** [comment]
Nice job

**Comment by munniomer** [comment]
Nice work

**Comment by Ogutu-Brian** [comment]
This is cool!

**Comment by billthebuilder** [comment]
Awesome stuff right there

**Comment by wachiranduati** [comment]
Niiiice

**Comment by Siffersari** [comment]
Really creative. Some of your initial commits have a tick beside them. How is that so?

**Comment by a-braham** [comment]
Some nice work right there

**Comment by Siffersari** [comment]
Hello again Tirgei, I have noticed something of a slight error. It seems you are merging into *master* from the feature branch. I believe we are supposed to be merging into *gh-pages* instead. If anyone could second, dismiss or clarify on this. I will be really greatful

**Comment by Siffersari** [comment]
@tirgei  Please look into my agenda above.

**Comment by khwilo** [comment]
> Hello again Tirgei, I have noticed something of a slight error. It seems you are merging into _master_ from the feature branch. I believe we are supposed to be merging into _gh-pages_ instead. If anyone could second, dismiss or clarify on this. I will be really greatful

@tirgei, @Siffersari  is right. Every feature should be merged to gh-pages not master.

**Comment by Siffersari** [comment]
Thank you for the feedback @khwilo

**Comment by tirgei** [comment]
> Really creative. Some of your initial commits have a tick beside them. How is that so?

I'm not sure about the ticks. Though I think that's where I created the branch, after the second tick

**Comment by tirgei** [comment]
@Siffersari @khwilo thank's for the correction guys. Let me update

**Pull request merged**
